export enum HistoryLogEntityEnum {
  None = 0,
  Referral = 1,
  Appointment = 2,
  Patient = 3,
  Clinic = 4,
  Clinician = 5,
  Client = 6,
  ClientUser = 7,
  Product = 8,
  Location = 9,
  Site = 10,
  Room = 11,
  Contract = 12,
  Invoice = 13,
  Department = 14,
  TermsAndConditions = 15,
  PatientDocument = 16,
  MriRequest = 17,
}
